### ISSUE TITLE
Variables don't parse correctly

### ISSUE THREAD

**Issue by BonfireScratch** [N-language/N-#10]
**Describe the bug**
Variables don't parse correctly

**To Reproduce**
1. Input `var x = 9`
2. Input `var y = 18`
3. See output under _--Environment--_
4. It says {"y": 18}

**Expected behavior**
It should say {"x"; 9, "y": 18}

**Desktop:**
 - OS: Windows 7 Ultimate

**Comment by BonfireScratch** [comment]
I am not quite sure if it works for others so I would like you to do some testing @otsfan204 @SimpleBinary

**Comment by otsfan203** [comment]
I'll check it out!

**Comment by SimpleBinary** [comment]
@BonfireScratch I get the issue on Windows 10, @Dandigit Do you get the issue on Linux?

**Comment by SimpleBinary** [comment]
@BonfireScratch I have debugged and found the problem, but I'm finding it really hard to fix. The problem is this:
Every time that `main.py` calls `interpreter.py` when there is a variable expression, it does add the value, but this is another problem with the dict `self.variables`.

I'll explain it like this, here are the key component of `interpreter.py` when it comes to setting variables:
```python
# All in the class parser
def __init__(self, tokens):
        self.tokens = tokens
        self.token_index = 0
        self.transpiled_code = ""
        self.varObj = varObject.VariableObject()

# Skip a bit

def parseVariableDeclaration(self, token_stream):
        tokens_checked = 0

        name = ""
        operator = ""
        value = ""

        for token in range(0, len(token_stream)):
            token_type = token_stream[tokens_checked][0]
            token_value = token_stream[tokens_checked][1]

            if token == 1 and token_type == "IDENTIFIER":
                name = token_value
            elif token == 1 and token_type != "IDENTIFIER":
                print(token_type)
                print("N# ERROR: Invalid variable name " + token_value)
                quit()
            elif token == 2 and token_type == "OPERATOR":
                operator = token_value
            elif token == 2 and token_type != "OPERATOR":
                print("N# ERROR: Invalid or missing assignment operator")
                quit()
            elif token == 3 and token_type in ["STRING", "INTEGER", "IDENTIFIER"]:
                value = token_value
            elif token == 3 and token_type not in ["STRING", "INTEGER", "IDENTIFIER"]:
                print("N# ERROR: Invalid variable assignment value " + token_type)
                quit()

            tokens_checked += 1
        
        self.varObj.set_variable(name, operator, value)
        print("-- ENVIRONMENT --")
        print(self.varObj.variables)

        self.token_index += tokens_checked
```
> Every time you call `interpreter.py`, the firs function __init__ runs, meaning it calls `varObject.py` every time, which calls `varObject.py` every time.

> As for the second function, parseVariableDeclaration(), it calls the function that sets the variable in `varObject.py`

Now lets look at the key components of `varObject.py`:
```python
class VariableObject(object):
    
    def __init__(self):
        self.exec_string = ""
        self.variables = {}

    def set_variable(self, name, operator, value):
        self.exec_string += name + " " + operator + " " + value + "\n"
        self.variables[name] = value
```
First, the __init__, **every time it is called it sets the variable dict to {}**, so when the set_variable is called, it adds a new item to a **blank** dictionary, meaning only the most-recently declared variable is stored.

Putting it basically, `main.py calls interpreter.py calls varObject.py which creates a new dict`, so every time you set a variable, the previous variable's value is discarded.

As for what to do, you have to store the variables in a place that will not get reset every time you try and set a file, as there is no *reliable* way of checking it exists, as it always creates a local variable in the if statement, try statement or anything else you try inside a class, I'll still try to figure out a way to do it though.

- SimpleBinary

**Comment by Dandigit** [comment]
@BonfireScratch @SimpleBinary I've got the solution to this. You must keep a consistent environment in the REPL by using the same interpreter. I'll open a PR in a minute to explain.

**Comment by Dandigit** [comment]
Merge #14 to fix.
